### ISSUE TITLE
SEQ-3 gate events are skipped

### ISSUE THREAD

**Issue by sanderbaan** [VCVRack/Fundamental#1]
There is something weird going on with the seq-3 module. When you activate all gates no gate is being outputted on the Gates output of the module, also when two gates next to each other(for example 1 and 2) only the first gate is outputted. Sometimes I also get ghost notes, set a gate on step 1 then another gate event is send out which is not set anywhere. Actually when you set to gates next to each other 1 and 2 then first gate is send but then on position another one is send but the event is not there...

**Comment by pixelrust** [comment]
I'm confused as well by SEQ-3, but I'm also new to modular sequencers.

Was this issue closed because this is the expected SEQ-3 behaviour? 
If yes, can someone kindly point me to appropriate documentation? I looked for it but couldn't find any.

**Comment by jackokring** [comment]
A gate is not a trigger. A gate is not an event pulse, although if you
shorten the gate time, and feed the gate into an input of an envelope
generator and feed the envelope out to a VCA on the signal, you may
get the kind of thing your after.

On 19/09/2017, pixelrust <notifications@github.com> wrote:
> I'm confused as well by SEQ-3, but I'm also new to modular sequencers.
>
> Was this issue closed because this is the expected SEQ-3 behaviour?
> If yes, can someone kindly point me to appropriate documentation? I looked
> for it but couldn't find any.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/VCVRack/Fundamental/issues/1#issuecomment-330544964


-- 
http://www.kring.co.uk
