### ISSUE TITLE
Parametra feature re-request

### ISSUE THREAD

**Issue by tylerpolzin** [VCVRack/Fundamental#101]
Sometime between version 0.6 and 1.0, the ability to Ctrl+drag filter nodes in Parametra disappeared.  Could you please add it back in?

**Comment by AndrewBelt** [comment]
This is the issue tracker for the VCV Fundamental plugin, so I'm closing. Customers should contact@vcvrack.com for commercial VCV plugin bug reports and feature requests, but I'll add this to our internal issue tracker.
