### ISSUE TITLE
Range control on SEQ-3

### ISSUE THREAD

**Issue by benirose** [VCVRack/Fundamental#109]
I'm having a hard time dialing in my desired sequences due to the giant range on the sequencer. I'm wondering if it'd be difficult to add a range limitation, either via a knob or the context menu. This could help make more musical sequences much faster. Even just 1v, 2v, 5v, 8v would be good options I think. I understand patching in an attenuator would help with this, but it can be hard to dial in.

**Comment by AndrewBelt** [comment]
I'm rejecting this feature request. The range is 0-10V. If you desire a different range, use an attenuator module such as VCV 8vert.
