### ISSUE TITLE
some graphics issues with SEQ3 and ADSR modules

### ISSUE THREAD

**Issue by davephillips** [VCVRack/Fundamental#11]
Linux Fedora 23 GCC 5.3.1
VCV Rack dev version

SEQ3: Inner (green) light is not centered.
ADSR: Panel graphics wrong size.

I'm not sure if I can post images here, so I've placed one here:

http://linux-sound.org/images/fundamentalerrors.png 

Btw, please advise if reports like this are welcome. I realize that the dev stuff is under constant change, I don't want to post irrelevant reports.

**Comment by AndrewBelt** [comment]
Working on it

**Comment by fenykep** [comment]
ADSR graphics fixed.

**Comment by AndrewBelt** [comment]
Oh right, forgot to close
