### ISSUE TITLE
The output label of Octave should be OUT, not OCT

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Fundamental#112]
The output signal isn't related to octaves, so it doesn't make sense to call it an "octave output".

**Comment by squinkylabs** [comment]
looks like this one can be closed?
![image](https://user-images.githubusercontent.com/16314838/144092213-9b455ba7-2ab4-4fb5-97a2-5a93e7af45ca.png)

**Comment by AndrewBelt** [comment]
Yes, fixed.
