### ISSUE TITLE
Trigger source set to "External" by default

### ISSUE THREAD

**Issue by modlfo** [VCVRack/Fundamental#132]
I noticed that when connecting the scope my signals did not look well. It was because the trigger source was set to "External" by default.

Is that by design? or is it a small mistake?

**Comment by AndrewBelt** [comment]
This is by design. Because Scope now waits indefinitely for a trigger before recording, users will get confused if they send it a signal that doesn't pass the trigger threshold and nothing appears on Scope. External with no cable patched into EXT means that Scope does not wait on a trigger.
