### ISSUE TITLE
Incorrect regex in helper.py

### ISSUE THREAD

**Issue by PrittotoPritto** [VCVRack/Fundamental#146]
In helper.py the regex to get the color of an item reads `r'fill:\S*(#[0-9a-fA-F]{6})'` which may skip over valid colors closer to the fill label, in my case it got the stroke color instead. Changing it to `r'fill:\S*?(#[0-9a-fA-F]{6})'` worked to fix it.

**Comment by AndrewBelt** [comment]
Hello @PrittotoPritto, this is the issue tracker for VCV Free modules. Could you send this to [VCV Support](https://vcvrack.com/support) so we can notify you when the issue is handled?
