### ISSUE TITLE
V/oct input in SEQ3 for entering notes

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Fundamental#18]
Would it be possible to add a V/oct input in Fundamental's SEQ3 module, so that when we right click one of the 24 knobs, it would set that knob to the current V/oct input? When no cable is connected to that input, it would revert to the current default behavior of simply resetting the knob to zero. 

This would be a very useful addition, since as it is now, I find it takes a fair amount of time and adjustments to setup a sequence of notes in SEQ3 (I try not to use quantizers in SEQ3's output). 

The use case I'm assuming here is when we want to enter sequences of notes using a midi keyboard, the Autodafe keyboard or anything else that generates pitch-correct CVs. This would make it such that we can sequence notes in a more real-time manner, without the need for using loopers.

If this does not adhere to the design principles of the Fundamental modules, please let me know and I'll remove the issue. Thanks!

P.S. The new sequential switches are a great addition btw!

**Comment by AndrewBelt** [comment]
Rack doesn't support "mechanized knobs", so you can't control a knob's position with CV.

There might be another sequencer that fits your needs, which is implemented in a different way.

**Comment by MarcBoule** [comment]
Ok, thanks. I'll be looking into ML modules and Bidoo, perhaps something there will work. By the way, I don't know if it's the same thing as you mentioned, but Clement Foulc has mechanized the gain knob on his mixer modules, and it's quite neat. When you control the gain with a CV, you actually see the knob turn.

**Comment by AndrewBelt** [comment]
Yes, and his method will break with a future release unfortunately.

**Comment by MarcBoule** [comment]
Ok, good to know, and thanks for the followup!
