### ISSUE TITLE
Compilation error: `only virtual member functions can be marked 'override'`

### ISSUE THREAD

**Issue by KieranPringle** [VCVRack/Fundamental#19]
Get this on any file declaring either of 
```
void reset() override
void randomize() override
```
Rack revision: https://github.com/VCVRack/Rack/commit/2c17b654afc7e5c6e8e70f41df9dd3f8ad9dde24
Fundamental revision: https://github.com/VCVRack/Fundamental/commit/b54abba8585e39badd44e3c45ab38e1f758f65b7

This goes away if I roll back Rack to this revision:
https://github.com/VCVRack/Rack/commit/e60117701c2d45c5d0b9a8d929b02f6349e9fd80
Which is the commits before `Remove Module::reset(), Module::initialize(), and Module::randomize(), add onRandomize(), onReset(), onCreate(), and onDelete()`
https://github.com/VCVRack/Rack/commit/36cd050ba428a7687bea3a60b115c6c03c56bbdb

Building on OSX

**Comment by KieranPringle** [comment]
Workaround is to build off branch `v0.5` or one of the refs `v0.5.0`, `v0.5.1`

**Comment by AndrewBelt** [comment]
All the plugins are for v0.5 for now. I don't want to bother with branching/tagging the individual plugins since that's too messy.
