### ISSUE TITLE
Compiling fails with "Mutes" errors

### ISSUE THREAD

**Issue by CJunit** [VCVRack/Fundamental#23]
Hi there! Please bear with me, as I am an utter n00b. I just compiled Rack on my KDE Neon 5.11/kxStudio box, and it seems to run.

So I followed the readme instructions for populating the plugins folder, and make fails with this error:

> g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Mutes.cpp.o src/Mutes.cpp
> src/Mutes.cpp:34:7: error: ‘void Mutes::onReset()’ marked ‘override’, but does not override
>   void onReset() override {
>        ^
> src/Mutes.cpp:39:7: error: ‘void Mutes::onRandomize()’ marked ‘override’, but does not override
>   void onRandomize() override {
>        ^
> ../../compile.mk:53: recipe for target 'build/src/Mutes.cpp.o' failed
> make: *** [build/src/Mutes.cpp.o] Error 1

I don't know enough about C++ or Linux compiling for this to be useful info to me, but it might help somebody. Thanks VCV boffins for your efforts!

**Comment by CJunit** [comment]
For now I simply copied over the Fundamentals folder from the 0.5.1 binaries, and they seem to work fine - including Mutes.

**Comment by AndrewBelt** [comment]
`git checkout v0.5.1`

**Comment by CJunit** [comment]
> git checkout v0.5.1

There is no context, this does not mean anything to me. I tried adding this to your instructions in the readme, but the results are the same. I think I am building the wrong version of Rack also, as it is missing the download manager. 

> cjunit@cjunit-Studio-XPS:~/Rack/plugins$ git clone https://github.com/VCVRack/Fundamental.git
> Cloning into 'Fundamental'...
> remote: Counting objects: 426, done.
> remote: Compressing objects: 100% (25/25), done.
> remote: Total 426 (delta 10), reused 18 (delta 6), pack-reused 395
> Receiving objects: 100% (426/426), 582.22 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (278/278), done.
> Checking connectivity... done.
> cjunit@cjunit-Studio-XPS:~/Rack/plugins$ git checkout v0.5.1
> HEAD is now at 2c17b65... Add -lssl to Linux build
> cjunit@cjunit-Studio-XPS:~/Rack/plugins$ cd Fundamental
> cjunit@cjunit-Studio-XPS:~/Rack/plugins/Fundamental$ git submodule update --init --recursive
> cjunit@cjunit-Studio-XPS:~/Rack/plugins/Fundamental$ make
> g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/VCMixer.cpp.o src/VCMixer.cpp
> g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/VCA.cpp.o src/VCA.cpp
> g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/VCO.cpp.o src/VCO.cpp
> g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/SequentialSwitch.cpp.o src/SequentialSwitch.cpp
> g++ -fPIC -I../../include -I../../dep/include -DVERSION=0.5.1 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Mutes.cpp.o src/Mutes.cpp
> src/Mutes.cpp:34:7: error: ‘void Mutes::onReset()’ marked ‘override’, but does not override
>   void onReset() override {
>        ^
> src/Mutes.cpp:39:7: error: ‘void Mutes::onRandomize()’ marked ‘override’, but does not override
>   void onRandomize() override {
>        ^
> ../../compile.mk:53: recipe for target 'build/src/Mutes.cpp.o' failed
> make: *** [build/src/Mutes.cpp.o] Error 1

**Comment by AndrewBelt** [comment]
You're trying to build the Fundamental master branch with the v0.5 branch of Rack. Check out the v0.5.1 tag of Fundamental so the versions match.

**Comment by CJunit** [comment]
That is what I am trying to do! I tried typing "git checkout v0.5.1" in the Rack directory before this, but it did not make 0.5.1, as it is missing the download manager. I don't know whether or not the response "HEAD is now at 2c17b65... Add -lssl to Linux build" means that I am supposed to do something. Sorry that I am so confused. I can access the 0.5.1 tag from the web page and download a zip, except then I can't clone the submodules as per instructions:

> cjunit@cjunit-Studio-XPS:~$ cd Rack-0.5.1/
> cjunit@cjunit-Studio-XPS:~/Rack-0.5.1$ git submodule update --init --recursive
> fatal: Not a git repository (or any parent up to mount point /home/cjunit)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> 

I need to figure out how clone and checkout are used together. I am probably missing something fundamental to how git is supposed to work. I have been searching online for hours, but the problem might be too simple for an answer.

**Comment by AndrewBelt** [comment]
Double check the directory you're in when running that.  You're in a Rack-owned directory. You need to be in the Fundamental directory.
