### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by shimpe** [VCVRack/Fundamental#24]
Most plugins fail to build with error messages like the following:

src/SEQ3.cpp:109:7: error: ‘void SEQ3::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^~~~~~~
src/SEQ3.cpp:115:7: error: ‘void SEQ3::onRandomize()’ marked ‘override’, but does not override
  void onRandomize() override {
       ^~~~~~~~~~~

**Comment by shimpe** [comment]
ok, it does build after checking out the most recent tags. 
Maybe best to add a warning to the README files?

**Comment by AndrewBelt** [comment]
Duplicate of https://github.com/VCVRack/Fundamental/issues/23

Will add to README
