### ISSUE TITLE
Add an WAV Recorder 

### ISSUE THREAD

**Issue by Luraktinus** [VCVRack/Fundamental#27]
Hi, i love to work with your software, (i also got the paid VCV Plugins to support this project) 
my only wish is to add an WAV recorder to the default/fundamental plugins of VCV Rack, 
i imagine it to be simple to add.

Such a module would greatly improve my workflow and the sound quality of my audio files.

thanks~ Lue

**Comment by AndrewBelt** [comment]
I don't accept module requests for Fundamental.
There are around 500 third party plugins now, so there's bound to be one.

**Comment by Luraktinus** [comment]
well, so far i have not found one...  could you do a separate plugin then?

**Comment by Luraktinus** [comment]
well, there is one but it doesn't work

**Comment by Luraktinus** [comment]
i would pay for such a basic plugin if needed

**Comment by antoniotuzzi** [comment]
nysthi package has 2 audio recorder (2 tracks and 8 tracks) since november 16th

**Comment by Luraktinus** [comment]
ah ok
