### ISSUE TITLE
marked ‘override’, but does not override

### ISSUE THREAD

**Issue by ensonic** [VCVRack/Fundamental#28]
with git HEAD of today I get a bunch of:
````
src/Mutes.cpp:34:7: error: ‘void Mutes::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^~~~~~~
src/Mutes.cpp:39:7: error: ‘void Mutes::onRandomize()’ marked ‘override’, but does not override
  void onRandomize() override {
       ^~~~~~~~~~~
src/Unity.cpp:34:7: error: ‘void Unity::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^~~~~~~
src/Scope.cpp:68:7: error: ‘void Scope::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^~~~~~~
````

As a workaround, I used `make CXXFLAGS=-Doverride=`.

**Comment by AndrewBelt** [comment]
Disabling a warning which is trying to tell you something important is not a workaround. Read the Fundamental README, paying attention to the build instructions.

**Comment by ensonic** [comment]
@AndrewBelt please watch your tone. I am well aware that suppressing the warning is not a good idea. The issue seem that https://github.com/VCVRack/Rack is configured to clone v0.5 by default, but for the plugins this is not the case.

**Comment by AndrewBelt** [comment]
I'd be happier if you read the documentation or one of these duplicate issues: https://github.com/VCVRack/Fundamental/issues/22  https://github.com/VCVRack/Fundamental/issues/24 https://github.com/VCVRack/Fundamental/issues/21
Any suggestions that I can make this more clear? I'm out of ideas.

Rack v0.5 is a branch, while Fundamental uses only tags, and I can't make `git clone` check out a tag.

**Comment by ensonic** [comment]
I read the docs. I did not saw the closed dupes. TBH https://github.com/VCVRack/Rack/tree/master#building does not make it clear that Rack is going to be a branch and one must checkout the matching tag for the plugins.

**Comment by hanswright** [comment]
https://githubsatellite.com/code-of-conduct/
