### ISSUE TITLE
Plugins will not compile.

### ISSUE THREAD

**Issue by AndyWharfe** [VCVRack/Fundamental#30]
Good Day,

Just attempted to compile plugins on Windows platform and will not compile :(

src/Delay.cpp:78:7: error: 'struct rack::SampleRateConverter<1>' has no member named 'setRates'; did you mean 'setRatio'?
   src.setRates(ratio * engineGetSampleRate(), engineGetSampleRate());

It appears to me that your alteration made 18 days ago is the problem.

I've carried a few more checks and it appears that your onReset() Overide doesn't work either.

Andy W

**Comment by AndrewBelt** [comment]
https://github.com/VCVRack/Fundamental#building
Any suggestions to make this more clear?
