### ISSUE TITLE
Fundamentals Delay build error

### ISSUE THREAD

**Issue by pkarydogiannis** [VCVRack/Fundamental#31]
When building the Fundamentals module pack I get an error regarding the Delay module.
More specifically:
`src/Delay.cpp:78:7: error: no member named 'setRates' in
      'rack::SampleRateConverter<1>'
                src.setRates(ratio * engineGetSampleRate(), engineGetSam...
                ~~~ ^
1 error generated.
make: *** [build/src/Delay.cpp.o] Error 1`

Any fixes?

**Comment by AndrewBelt** [comment]
README

**Comment by furioncycle** [comment]
I got this error before make sure you are building on the branch that your
rack is on.

**Comment by pkarydogiannis** [comment]
Oh right! Thank you! missed the closed issues
