### ISSUE TITLE
Delay not doing anything on my build from master vs Rack master

### ISSUE THREAD

**Issue by PeterLeigh-awin** [VCVRack/Fundamental#32]
Hi,

I recently built Rack and Fundamental from their current master branches, and afterwards I noticed I didn't seem to get any delay output from the delay module, just dry.

I'm curious about whether this is just some error of mine while building, or if it's an actual code problem.

After a bit of experimentation, I found that the following diff at least restored some wet output, but the code is largely mysterious to me, so no claims as to the correctness of it!

```
diff --git a/src/Delay.cpp b/src/Delay.cpp
index a89c7d6..0978168 100644
--- a/src/Delay.cpp
+++ b/src/Delay.cpp
@@ -75,7 +75,7 @@ void Delay::step() {
                int inFrames = mini(historyBuffer.size(), 16);
                int outFrames = outBuffer.capacity();
                // printf(">\t%d\t%d\n", inFrames, outFrames);
-               src.setRates(ratio * engineGetSampleRate(), engineGetSampleRate());
+               src.setRates(engineGetSampleRate()/ratio, engineGetSampleRate());
                src.process((const Frame<1>*)historyBuffer.startData(), &inFrames, (Frame<1>*)outBuffer.endData(), &outFrames);
                historyBuffer.startIncr(inFrames);
                outBuffer.endIncr(outFrames);
```

**Comment by AndrewBelt** [comment]
libspeexdsp is not designed for smoothly varying the ratio, so in order to restore functionality of Delay, libsamplerate will need to be used within the Fundamental project.

**Comment by ndrspcfd** [comment]
Thanks, it does sound a bit rough :) I'll close this.

**Comment by PeterLeigh-awin** [comment]
Thanks, it does sound a bit rough.. :) I'll close this.
