### ISSUE TITLE
Allow user to select output routing on Audio Interface or dynamically add more outputs per selected interface

### ISSUE THREAD

**Issue by ham-steamer** [VCVRack/Fundamental#33]
If you are running an interface with more than 8 outputs and wish to use one of the outputs that is >8, you are currently unable to do so. It would be great to be able to selectively route outputs to preferred interface outputs or have the application dynamically create all available input/outputs per the selected device.

**Comment by AndrewBelt** [comment]
This is the incorrect repo for reporting this request.

I'm increasing the maximum ins/outs to 32/32, and it will dynamically rescale. Merging with https://github.com/VCVRack/Rack/issues/82
