### ISSUE TITLE
Scope time knob can only select two positions

### ISSUE THREAD

**Issue by WIZARDISHUNGRY** [VCVRack/Fundamental#37]
Rack version: v0.6 @ 0ba244e98f05ab36c46636c6c718f84af531d75e
OS: Mac

Trying to manipulate the "time" knob on the Scope only allows me to select the right most position. If I right click the knob, the 3 o'clock position may be selected. Randomize will select other values.

**Comment by AndrewBelt** [comment]
That was an unexpected one, thanks. Fixed in 10e751d
