### ISSUE TITLE
[Feature request] Add output to scope

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Fundamental#4]
Scope has an empty space, fit for an output. Then it could act as a passthrough without the need for multipliers. I propose to output the sum of X and Y signal.

**Comment by AndrewBelt** [comment]
With stackable cables, this would be redundant.

**Comment by Euphorbium** [comment]
Oh well. Already implemented it, but I can't update svg background.

**Comment by AndrewBelt** [comment]
Added stackable cables to Rack, so I'll close this now. That should solve the problem.
