### ISSUE TITLE
$(WGET) and $(UNTAR) undefined when building Fundamental

### ISSUE THREAD

**Issue by JasonBarile** [VCVRack/Fundamental#42]
I'm unable to build Fundamental on my Mac. Looking at the Makefile and build output, it seems that $(WGET) and $(UNTAR) are not defined at the time they're referenced in the makefile. Should a different makefile with definitions for these be included?

**Comment by WIZARDISHUNGRY** [comment]
My understanding is that target is only run after plugin.mk is included.

**Comment by JasonBarile** [comment]
Ah, nevermind. I must have been on an old branch or something. Now that I'm on master everywhere I'm building just fine.

**Comment by WIZARDISHUNGRY** [comment]
@JasonBarile you might want to consider using branch `v0.6`

**Comment by JasonBarile** [comment]
@WIZARDISHUNGRY I didn't see a v0.6 branch for Fundamental or the other plugins. Which branch should I use for those?

**Comment by WIZARDISHUNGRY** [comment]
Oh, master then!

**Comment by JasonBarile** [comment]
Ah, thanks. So v0.6 for Rack and master for plugins?
