### ISSUE TITLE
Possible mistake in ADSR.cpp line 44

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Fundamental#44]
Could there be a small mistake here in ADSR.cpp at line 44:

```float attack = clamp(params[ATTACK_INPUT].value + inputs[ATTACK_INPUT].value / 10.0f, 0.0f, 1.0f);```

The first `ATTACK_INPUT` should be `ATTACK_PARAM`?

**Comment by AndrewBelt** [comment]
Thanks, fixed in 5b9345f

**Comment by MarcBoule** [comment]
In looking again, I just noticed that the mis-labeling in the enums had no consequence and produced no ill-woking side effects in the module, but worth correcting anyways :-) 👍
