### ISSUE TITLE
Getting samplerate.h error when building Fundamental

### ISSUE THREAD

**Issue by 573** [VCVRack/Fundamental#46]
> rack_plugins_1      | ++ popd
rack_plugins_1      | ++ buildp https://github.com/VCVRack/Fundamental.git v0.6 --recursive
rack_plugins_1      | /build/Rack/plugins /build/Rack
rack_plugins_1      | +++ basename https://github.com/VCVRack/Fundamental
rack_plugins_1      | ++ ls /build/Rack/plugins/Fundamental
rack_plugins_1      | ++ git clone https://github.com/VCVRack/Fundamental.git
rack_plugins_1      | Cloning into 'Fundamental'...
rack_plugins_1      | +++ basename https://github.com/VCVRack/Fundamental
rack_plugins_1      | ++ pushd ./Fundamental
rack_plugins_1      | ++ shift
rack_plugins_1      | ++ git remote prune origin
rack_plugins_1      | /build/Rack/plugins/Fundamental /build/Rack/plugins /build/Rack
rack_plugins_1      | ++ git fetch
rack_plugins_1      | ++ git checkout v0.6
rack_plugins_1      | Already on 'v0.6'
rack_plugins_1      | Your branch is up-to-date with 'origin/v0.6'.
rack_plugins_1      | ++ shift
rack_plugins_1      | ++ [[ -n 1 ]]
rack_plugins_1      | ++ git submodule update --init --recursive
rack_plugins_1      | ++ shift
rack_plugins_1      | ++ [[ -n 0 ]]
rack_plugins_1      | ++ make
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VCMixer.cpp.o src/VCMixer.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VCA.cpp.o src/VCA.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VCO.cpp.o src/VCO.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/SequentialSwitch.cpp.o src/SequentialSwitch.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Mutes.cpp.o src/Mutes.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Unity.cpp.o src/Unity.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Scope.cpp.o src/Scope.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/LFO.cpp.o src/LFO.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/ADSR.cpp.o src/ADSR.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/8vert.cpp.o src/8vert.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/SEQ3.cpp.o src/SEQ3.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VCF.cpp.o src/VCF.cpp
rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/Delay.cpp.o src/Delay.cpp
rack_plugins_1      | src/Delay.cpp:5:24: fatal error: samplerate.h: No such file or directory
rack_plugins_1      | compilation terminated.
rack_plugins_1      | ../../compile.mk:64: recipe for target 'build/src/Delay.cpp.o' failed
rack_plugins_1      | make: *** [build/src/Delay.cpp.o] Error 1
vcvrackdocker_rack_plugins_1 exited with code 2

**Comment by AndrewBelt** [comment]
Thanks, I've revised the https://github.com/VCVRack/Rack#building-plugins section. The step I added was `make dep` before `make`.

**Comment by 573** [comment]
Thank you, I will try to test this later that day.

**Comment by 573** [comment]
Works.
