### ISSUE TITLE
ode API namespace missing?

### ISSUE THREAD

**Issue by 573** [VCVRack/Fundamental#50]
Build fails currently (baa041b) with:

> rack_plugins_1      | g++ -Wsuggest-override -std=c++11 -Idep/include -DSLUG=Fundamental -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/VCF.cpp.o src/VCF.cpp
rack_plugins_1      | src/VCF.cpp: In member function 'void LadderFilter::process(float, float)':
rack_plugins_1      | src/VCF.cpp:35:3: error: 'ode' has not been declared
rack_plugins_1      |    ode::stepRK4(0.f, dt, state, 4, [&](float t, const float x[], float dxdt[]) {
rack_plugins_1      |    ^
rack_plugins_1      | ../../compile.mk:64: recipe for target 'build/src/VCF.cpp.o' failed
rack_plugins_1      | make: *** [build/src/VCF.cpp.o] Error 1

Should it be `rack::ode::stepRK4`?

**Comment by AndrewBelt** [comment]
Have you updated your Rack source tree?

**Comment by 573** [comment]
That exactly was the reason!
So sorry, thanks Andrew!
