### ISSUE TITLE
v1 slug not found in manifest

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Fundamental#56]
v1.dev.4741892

Rack runs okay but cloning Fundamental-1, Befaco-1, Template-1 repo's or manually adding and make does not work. Worked okay on an earlier version of Rack-1. This is a clean clone btw.

Just get the message
`
make: jq: Command not found
make: jq: Command not found
../../plugin.mk:9: *** SLUG could not be found in manifest.  Stop.
`

same issue with `make dep` with fundamental-1
I checked all v1 manifests, all have the "slug":. It's probably something I overlooked to which I apologies in advanced!

 
Win 7

**Comment by AndrewBelt** [comment]
Install jq.

**Comment by Coirt** [comment]
What is that and where do I find it?

**Comment by Coirt** [comment]
If this is not a recent change, I should have this installed already no? Have the build instructions been updated to include this change or has it always been this way? I see it is included in `pacman -Su` though I'm not sure if that is recent or not, if it is not then I should have that already.

**Comment by AndrewBelt** [comment]
Use `pacman -S <packages>` to install packages.

**Comment by Coirt** [comment]
Right thanks is that `pacman -S <mingw-w64-x86_64-jq>` or `pacman -S mingw-w64-x86_64-jq` it is resent then?

**Comment by Razz21** [comment]
I have installed mingw-w64-x86_64-jq in mysys2, try to build plugin and got similar errors:
`
jq: error: Could not open file plugin.json: No such file or directory
jq: error: Could not open file plugin.json: No such file or directory
C:\Users\<username>\Documents\Rack-SDK/plugin.mk:9: *** SLUG could not be found in manifest. Stop.
`
