### ISSUE TITLE
Delay compile error (-fpermissive)

### ISSUE THREAD

**Issue by leopard86** [VCVRack/Fundamental#58]
Compiling Fundamental gives me this error:

src/Delay.cpp:76:20: error: invalid conversion from ‘const float*’ to ‘float*’ [-fpermissive]
    srcData.data_in = (const float*) historyBuffer.startData();
                    ^

I avoid tampering with the -f compile flags as I don't want to alter the compilation of other modules. For now I can quickly fix by removing the const attribute but a better solution is required.

My compiler:
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Maybe in later versions the policy with -fpermissive has changed.
Linux Mint, Rack v1.dev.df0c8cf

**Comment by AndrewBelt** [comment]
This was changed in libsamplerate 0.1.9. The question is: Why is it using < 0.1.9? Did you run `make dep` before building Fundamental?

**Comment by leopard86** [comment]
Yep but didn't submodule sync, thanks
