### ISSUE TITLE
bug: v1 scope double click, randomise

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Fundamental#59]
When you double click X scl or Y scl on Scope it does not intitialize the params.

Also randomising will randomise the buttons to a value of between 0 and 1.0 and hold the button state at 1 (appearing to be stuck at true).

**Comment by AndrewBelt** [comment]
I can't reproduce either of these behaviors.

**Comment by Coirt** [comment]
Sorry I'm on windows.

Randomise can also set x/y scl to values other than snap = true; e.g. 2.1456 clicking the button will round to the snap value.

**Comment by Coirt** [comment]
![scopeBug](https://user-images.githubusercontent.com/12150421/54075038-018a2580-4292-11e9-8afc-35cb8151b1ac.gif)

**Comment by Coirt** [comment]
I found a few more discrepancies should I save them up till you are ready for prober testing?

**Comment by AndrewBelt** [comment]
Thanks, changed API in 6fe14dc, which moves the responsibility of resetting and randomization from `Param` (back) to `ParamWidget`.

**Comment by Coirt** [comment]
No bother!

**Comment by Coirt** [comment]
Apologies Andrew where exactly does `.randomizable = false;` go now. 

I had it in config(), tried process(), and also where you set components I know you say ParamWidget could you link to a example line{} of where that is.

**Comment by AndrewBelt** [comment]
>Apologies Andrew where exactly does .randomizable = false; go now.

To disable randomization of a knob, override `randomize()`.
