### ISSUE TITLE
VCO1 - exponential fm - question

### ISSUE THREAD

**Issue by miguel-negrao** [VCVRack/Fundamental#62]
Hi 

From looking at the code it appears VCO1 does exponential fm:

```
float pitchFine = 3.0f * quadraticBipolar(params[FINE_PARAM].value);
	float pitchCv = 12.0f * inputs[PITCH_INPUT].value;
	if (inputs[FM_INPUT].active) {
		pitchCv += quadraticBipolar(params[FM_PARAM].value) * 12.0f * inputs[FM_INPUT].value;
	}
	oscillator.setPitch(params[FREQ_PARAM].value, pitchFine + pitchCv);
```

Out of curiosity, was this a deliberate choice ? I've read that linear fm will keep the same fundamental when changing the modulation depth, while exponential doesn't, in the analog domain: 

https://learningmodular.com/understanding-the-differences-between-exponential-linear-and-through-zero-fm/

**Comment by AndrewBelt** [comment]
>was this a deliberate choice ?

Yes.
