### ISSUE TITLE
LFO polyphony problems

### ISSUE THREAD

**Issue by martin-lueders** [VCVRack/Fundamental#66]
The LFO-2 stops when removing a polyphonic cable which was connected to FM.
Also, the number of channels of OUT is not updated when removing the cable from FM.

LFO-1 seems to behave correctly.

This happens on Win 7 (other OSs not tested)

**Comment by AndrewBelt** [comment]
Thanks, I wrote a blog post about this. https://community.vcvrack.com/t/rack-v1-development-blog/1149/508?u=vortico
Will fix Fundamental soon.
