### ISSUE TITLE
Compile error building v1

### ISSUE THREAD

**Issue by SteveRussell33** [VCVRack/Fundamental#68]
g++ -std=c++11 -Wsuggest-override -Idep/include -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Delay.cpp.o src/Delay.cpp
src/Delay.cpp:2:10: fatal error: samplerate.h: No such file or directory
    2 | #include "samplerate.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:62: build/src/Delay.cpp.o] Error 1

**Comment by SteveRussell33** [comment]
Oops forgot make dep; closing

**Comment by AndrewBelt** [comment]
Attach your log.txt file after running Rack

**Comment by SteveRussell33** [comment]
https://drive.google.com/open?id=10MoeXZUOjUSyWf9ntzpQZpSljxlCn0ZG

**Comment by AndrewBelt** [comment]
It says it loads fine...

**Comment by SteveRussell33** [comment]
Not loading the SVG files?
https://drive.google.com/open?id=1_RDJM3Y1kGkddF4e3_eTdvSk0VemM_eb

**Comment by AndrewBelt** [comment]
Did you try searching for one of the module, like `VCV VCO`?

**Comment by SteveRussell33** [comment]
Oh right got it!
There're under VCV not Fundamental a la 0.6.2

Thx
Closing

**Comment by AndrewBelt** [comment]
Ah, yes. That was fixed in v1 since their brand is of course "VCV".
