### ISSUE TITLE
? Noise on Auto Channels with poly Merge

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Fundamental#69]
So I have a polyphonic mixer which uses getChannels() in a for loop to set channels to an array[16]. When Merge is set to Auto there is noise on the disconnected channels. I had a feeling it is because the array is not populated with values when there is disconnected channels, index positions only get initialized when channels are connected**,  I tested that theory and it does in fact fix the issue - initializing the array[16] with {0.f} on each index.

_**i.e. 13 channels connected would mean there is 3 index position with no value._ 

But just curious about the noise from the non initialized array values. Thought I'd share and just check I haven't stumbled upon an issue with using Auto channels. When channels are set to manual the array initializes values to `0.f` 

I was checking which channels the noise was coming from and it was not coming through on all channels which was odd.

![AutoChannelNoise](https://user-images.githubusercontent.com/12150421/59140175-32adeb00-8992-11e9-85f9-bf6f9dcefab8.gif)

**Comment by AndrewBelt** [comment]
I'm not sure what Merge has to do with it. In your module, you're not setting `array[n]` for `n >= inputs[...].getChannels()`, so you should expect undefined values there.

**Comment by Coirt** [comment]
I figured that much, initializing the array is the fix! Just curious as to what the noise is. It does not seem to be on every channel/index position which it should be and it is a different sound for each channel batch (1-4) also it has different ±phase. Shouldn't it be the exact same noise on every channel that is not initialized.

**Comment by AndrewBelt** [comment]
When you have undefined data on the stack, its data is usually "defined" by previously called functions.
