### ISSUE TITLE
VCV Octave (OCT) generates no output for no input in 1.0

### ISSUE THREAD

**Issue by expertsleepers** [VCVRack/Fundamental#70]
### Details

Operating system: mac
Rack version: 1.dev.b4bd09a
Hardware relevant to your issue (e.g. graphic card model, audio/MIDI device):

### Expected behavior

With no input, pressing octave jump buttons outputs integer volts. (This is the 0.6 behaviour.)

### Actual behavior

No output.

**Comment by AndrewBelt** [comment]
Thanks, fixed in b28ebf4

**Comment by ROGAVKA** [comment]
I still observe this bug in the official 1.0.0 release, is that ok?

**Comment by AndrewBelt** [comment]
@ROGAVKA You're still using the dev version of Fundamental. Delete `<Rack user folder>/plugins-v1/Fundamental` and relaunch Rack.
