### ISSUE TITLE
Fundamental plugin fails when building

### ISSUE THREAD

**Issue by circadiansound** [VCVRack/Fundamental#71]
When attempting to build the Fundamental plugin in the latest built from source version of Rack V1, with OS 10.11.6 and Xcode 8.2.1, I get the following error:

```
../../include/dsp/ode.hpp:61:6: error: variable length array of non-POD element
      type 'rack::simd::Vector<float, 4>'
        T k1[len];
            ^
src/VCF.cpp:39:8: note: in instantiation of function template specialization
      'rack::dsp::stepRK4<rack::simd::Vector<float, 4>, (lambda at
      src/VCF.cpp:39:36)>' requested here
                dsp::stepRK4(T(0), dt, state, 4, [&](T t, const T x[], ...
                     ^
src/VCF.cpp:152:12: note: in instantiation of member function
      'LadderFilter<rack::simd::Vector<float, 4> >::process' requested here
                        filter->process(input, args.sampleTime);
                                ^
1 error generated.
make: *** [build/src/VCF.cpp.o] Error 1
```

Additional unrelated side note: I mentioned earlier that I wasn’t able to build the Audible Instruments plugin, but since the recent updates it now builds successfully :-)

**Comment by AndrewBelt** [comment]
Possibly fixed in bb34db4 of Rack. Pull Rack and recompile.

**Comment by AndrewBelt** [comment]
Had to revert commit. You could check out that commit, build Fundamental, and then check out `v1` in Rack again. But you won't be able to build Fundamental on Xcode 8 again.

**Comment by circadiansound** [comment]
I just tried a git pull and recompile of Rack, but it seems like the same version recompiled. I’ll just reclone the repo and try again to see if bb34db4 builds. The version I have working at the moment is the bd... version.

Are you saying Xcode 8 won’t work anymore for building. I’m not sure I can upgrade this laptop past 10.11.

**Comment by circadiansound** [comment]
I’m not quite sure what the terminal command is for checking out the previous commit (bb34db4). I’m still new to all this and leaning, so please forgive my ignorance. I built 1ea9afc and it runs just fine. Like you mentioned above, I’m unable to build the fundamental plugin. I am able to drag in the compiled Binary from a previous stable release, and it seems to work just fine for now.

I was able to build the Audible Instruments against the 1ea9afc commit, which I assume is the latest. So, it seems this is specific to some of the external dependencies that the fundamental plugin requires for building which are incompatible with Xcode 8.2.1.

If I know what to enter into terminal to checkout the bb34db4 commit, I’d be happy to perform a temporary rebuild and see if the fundamental plugin builds against that version with my setup. I’ll just backup the current build I have running before hand.

**Comment by circadiansound** [comment]
I think it’s safe to close this now, since we now know I was experiencing a compatibility issue.
