### ISSUE TITLE
Octave right-click does not initialize like in 0.6.2c

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Fundamental#74]
Win10, Rack and Fundamental latest v1 builds.

In Octave v0.6.2c, right-clicking the octave section on the module used to reset the octave choice to the central position. Now in v1, the right-click does the same thing as left-click. Since there is the code shown below in the `OctaveButton` struct, it should actually work like before, so unless I'm misunderstanding something, it may indicate a problem.

```
	void onButton(const event::Button &e) override {
		if (e.button == GLFW_MOUSE_BUTTON_RIGHT && e.action == GLFW_PRESS) {
			module->octave = 0;
			e.consume(this);
			return;
		}
		OpaqueWidget::onButton(e);
	}
```

**Comment by AndrewBelt** [comment]
Thanks, fixed in 270a857
