### ISSUE TITLE
Sequential Switch 2 in 1.0

### ISSUE THREAD

**Issue by Cleanthis6** [VCVRack/Fundamental#77]
In SS-2 only the first input is working, in the 3 others it's like i've connect nothing in them

Windows 10
Rack 1.0

**Comment by AndrewBelt** [comment]
Did you download dev builds of Rack before installing Rack 1.0.0? If so, delete the `<Rack user folder>/plugins-v1/Fundamental` folder and restart Rack.

**Comment by Cleanthis6** [comment]
It worked, thank you !
