### ISSUE TITLE
MUTES LED "toggle" button tooltip not consistent in V1

### ISSUE THREAD

**Issue by salvolm84** [VCVRack/Fundamental#79]
In MUTES (just for example) the new V1 parameter tooltip on the mute buttons does not reflect the actual button state.
This is because these toggle buttons are actually implemented by temporary switches that flip the internal ON-OFF state on each button press, rather than actual toggle buttons.

**Comment by AndrewBelt** [comment]
No possible solution, closing.

**Comment by salvolm84** [comment]
I think the solution is to replace those buttons with something like:
```c
struct ToggleButton : app::SvgSwitch {
	ToggleButton () {
		addFrame(APP->window->loadSvg(asset::plugin(pluginInstance, "res/button_off.svg")));
		addFrame(APP->window->loadSvg(asset::plugin(pluginInstance, "res/button_on.svg")));
	}
};
```
in this way the tooltip will show the correct button state.
