### ISSUE TITLE
LFO-1 clamp config value for pw

### ISSUE THREAD

**Issue by Coirt** [VCVRack/Fundamental#83]
I am using the below in my own LFO which is based on LFO-1 and 2.  It works quiet nicely and is a little more correct than ±50% reported on the tooltip.

Firstly, this is okay to do in the config?
Request to be added to LFO-1.

Proposed change: https://github.com/VCVRack/Fundamental/blob/v1/src/LFO.cpp#L113
`configParam(PW_PARAM, 0.f, 1.f, 0.5f, "Pulse Width", "%", 0.f, clamp(100.f, 1.f, 99.f), -49.5f);`

**Comment by AndrewBelt** [comment]
I suppose it makes sense to actually limit the param itself. Review 770e045

**Comment by Coirt** [comment]
Or that :laughing: Is clamped in setPW() anyway.
```
void setPulseWidth(T pw_) {
		const T pwMin = 0.01f;
		this->pw = clamp(pw_, pwMin, 1.f - pwMin);
	}
```

**Comment by AndrewBelt** [comment]
This commit reduces the range of the param itself, so the display value ranges from 1-99% rather than 0-100%, which would be incorrect. This was the point of your issue.

**Comment by Coirt** [comment]
What I was trying to convey: A pulse width can not be 0% (0v, no pulse) or 100% (10v, no pulse). The config clamps already (min, max, default) and I was putting a clamp on the clamp. So I think your way is correct as it is equal to the clamp put on the values in the struct for pulseWidth, when scaled up 1%-99%.

If it was `0.02f, 0.98f, 0.5f` then that would be incorrect because it is already clamped to `0.2f` when sent to setPulseWidth() and can't reach `0.01f`
