### ISSUE TITLE
Fundamental VCO's : Oscillator Sync now produces extreme aliasing

### ISSUE THREAD

**Issue by Amy-Triptyline** [VCVRack/Fundamental#87]
MacbookPro 10.13.6 High Sierra / Rack 1.1.2

Oscillator Sync on both Fundamental VCO-1 and VCO-2 now produces extreme aliasing in both Hard and Soft Sync modes and in both Analog and Digital modes.

The problem does not reproduce with Squinky labs Fundamental VCO-1 as an example reference to compare at the same sample rate. (48,000)

Screen shots in the attachment below show :

"Previous" = Rack V0.6.2c 
"Current"   = Rack V1.1.2

Screen shots show the output of the slave Oscillator an octave higher than the master, neither VCO-1 / VCO-2 , Hard/Soft or Analog/Digital modes bear any relevance as the aliasing reproduces across all.

![Screen Shot 2019-07-21 at 13 52 55](https://user-images.githubusercontent.com/15366945/61590271-f095dd00-abbe-11e9-9ae0-80c43a138d06.png)

**Comment by AndrewBelt** [comment]
Probably a factor of -1 somewhere.

**Comment by kdunee** [comment]
Hi, I looked into the aliasing issue in hard sync and found this:
 
https://github.com/VCVRack/Fundamental/blob/ed19fbae2d9dbb495456051ae98201b93d3996b4/src/VCO.cpp#L134

changing it to

`T newPhase = simd::ifelse(sync, (1.f - syncCrossing) * deltaPhase, phase); `

removes the aliasing.

I also believe that sync detection should be done before checking the phase crossings to avoid unnecessary BLEPs in case we're going to be syncing in this frame and producing a BLEP anyway.

**Comment by AndrewBelt** [comment]
@kdunee Thanks, fixed in db0c7a6
