### ISSUE TITLE
Bug Missing svg for green slider

### ISSUE THREAD

**Issue by Petervos2018** [VCVRack/Fundamental#96]
I think something is missing from the 1.3.0 update.

![GreenSliderBug](https://user-images.githubusercontent.com/46076474/67143993-e349c680-f271-11e9-9cb7-79ebb8eabdba.png)

**Comment by AndrewBelt** [comment]
That's odd, can you post the log.txt entry that says WARN?

**Comment by Petervos2018** [comment]
[0.728 warn src/window.cpp:75] Failed to load SVG C:\PROGRA~1\VCV\Rack115/res/ComponentLibrary/LEDSliderHandle.svg

**Comment by AndrewBelt** [comment]
Thanks, fixed in c4194cd. Releasing Fundamental 1.3.1 now.

**Comment by AndrewBelt** [comment]
Ahh, this is because you're using an old version of Rack. If you upgrade to Rack v1.1.5, it would have been fixed. However, this update makes it display correctly old versions of Rack, so it was worth doing.

**Comment by Petervos2018** [comment]
I'm using 1.1.5 is there a newer version ?

**Comment by AndrewBelt** [comment]
What was the solution?

**Comment by Petervos2018** [comment]
Using the updated Fundamental 1.3.1 
There is NO LEDSliderHandle.svg in the component library of 1.1.5 on Windows.
