### ISSUE TITLE
Nois: White and Black spectrums are identical

### ISSUE THREAD

**Issue by MarcBoule** [VCVRack/Fundamental#97]
I'm noticing that the spectrum of white and black noises are practically identical, and I'm wondering if this is indicative of a problem or if this is intended.

![image](https://user-images.githubusercontent.com/33604154/67144351-820afe80-f243-11e9-95ea-b200bbd8f9e6.png)

**Comment by AndrewBelt** [comment]
This is intended. See https://vcvrack.com/Fundamental.html#Noise

**Comment by MarcBoule** [comment]
I should know better by now and should have RTFM :-)

By the way, when I read the Black noise types on wikipedia, I was kind of thinking you would do something funky with that one. With low enough temperature, black body radiation noise can be audible, and there is even Hawking radiation of black holes that has a peak in the audio range, according to the 4th item here:
https://en.wikipedia.org/wiki/Colors_of_noise#Black_noise

Fun stuff!

**Comment by AndrewBelt** [comment]
Black-body would be a bit like A-weighted (not inverse), so it was considered. Also Geiger counter / Poisson proces pulses, 1/f^β distributions β>2, etc. But the idea behind VCV Noise was for it to be listenable audio sources only. We have other modules planned that generate random triggers and such, and are better suited for it.
